export default {
  LOAD_USER: "LOAD_USER",
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  LOAD_PRODUCTS: "LOAD_PRODUCTS",
  NEXT_CAROUSEL: "NEXT_CAROUSEL",
  LOAD_CART: "LOAD_CART",
  CREATE_CART_ITEM: "CREATE CART_ITEM",
  UPDATE_CART_ITEM: "UPDATE CART_ITEM",
  DELETE_CART_ITEM: "DELETE CART_ITEM"
};