export default {
  LOAD_USER: "LOAD_USER",
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  LOAD_PRODUCTS: "LOAD_PRODUCTS",
  NEXT_CAROUSEL: "NEXT_CAROUSEL",
};